version: "3"
services:
  R:
    image: rocker/verse:uva
    build:
      context: .
      dockerfile: UVA-Rockerfile
    container_name: R-c
    volumes:
      - "~/Code/studies/5614/analysis/questionnaires:/home/rstudio/src"
      - "~/.vscode:/home/rstudio/.vscode-server"
    user: rstudio
    working_dir: /home/rstudio/src
    # make it restart automatically
    restart: always
    deploy:
      resources:
        limits:
          memory: 5G
          cpus: "2"
